const AREAS=['App Builder','Workflows','Integrations','ToolJet Database','AI / MCP','Permissions / RBAC','GitSync / CI/CD','Observability','Enterprise Deployment'];

const synthetic=[
['SC-01','Northstar Labs','Enterprise','Our admin team cannot easily tell whether a permission change affected one app or an entire workspace.','Permissions / RBAC','S2',5,3],
['SC-02','Atlas Retail','Mid-market','A workflow failed after an API schema changed and the operator only discovered it after a downstream task was missed.','Workflows','S2',4,3],
['SC-03','Nova Logistics','Enterprise','We need a clearer review step before agent-generated changes are promoted to production.','AI / MCP','S2',5,4],
['SC-04','Pine Health','Mid-market','Builders want to know which REST queries are duplicated across apps before maintaining them separately.','Integrations','S3',3,3],
['SC-05','Orbit Finance','Enterprise','Security reviewers want a concise record of what changed, who initiated it and what validations passed.','GitSync / CI/CD','S2',5,3],
['SC-06','Meridian Tools','Mid-market','Users want one place to see degraded integrations before reporting an internal app bug.','Observability','S3',3,3],
['SC-07','Ridge Systems','Mid-market','Database admins want clearer warnings before schema changes that may break existing app queries.','ToolJet Database','S2',4,3],
['SC-08','Vertex Commerce','Enterprise','Our security review needs to know what an AI coding agent changed and who initiated it.','AI / MCP','S2',5,3],
['SC-09','Copper Cloud','Startup','We need a faster way to duplicate an internal tool pattern across teams without copying every query manually.','App Builder','S3',3,2],
['SC-10','Juniper Media','Mid-market','A workflow can be valid but still produce a bad business outcome; we want lightweight test cases before activation.','Workflows','S2',4,3],
['SC-11','Nimbus Energy','Enterprise','Self-host upgrades are difficult to coordinate across environments and ownership is unclear.','Enterprise Deployment','S2',4,2],
['SC-12','Atlas Foods','Mid-market','Users want a single place to see which integrations are degraded before reporting an internal app bug.','Observability','S3',3,3]
].map((x,i)=>({id:x[0],source:'Synthetic customer',account:x[1],segment:x[2],title:x[3],raw:x[3],area:x[4],severity:x[5],impact:x[6],reach:x[7],evidence:3,created:new Date(Date.now()-i*172800000).toISOString(),url:'',state:'Awaiting review',summary:x[3],action:'Validate frequency with similar accounts; define the smallest reversible product change.',notes:''}));

let github=[];
let selected=null;
let decisions=JSON.parse(localStorage.getItem('signalops_decisions')||'{}');
const sevWeight={S1:5,S2:4,S3:2.5,S4:1};

function esc(v){return String(v??'').replace(/[&<>"']/g,m=>({'&':'&amp;','<':'&lt;','>':'&gt;','"':'&quot;',"'":'&#39;'}[m]))}
function score(s){return Math.round((s.impact*sevWeight[s.severity]+s.reach*2+s.evidence*1.5)*10)/10}
function inferArea(text){const t=(text||'').toLowerCase();if(t.includes('workflow'))return'Workflows';if(t.includes('permission')||t.includes('role'))return'Permissions / RBAC';if(t.includes('database')||t.includes('table'))return'ToolJet Database';if(t.includes('mcp')||t.includes('agent')||t.includes(' ai '))return'AI / MCP';if(t.includes('git')||t.includes('deploy')||t.includes('release'))return'GitSync / CI/CD';if(t.includes('api')||t.includes('integration')||t.includes('oauth'))return'Integrations';if(t.includes('log')||t.includes('monitor')||t.includes('observ'))return'Observability';if(t.includes('docker')||t.includes('kubernetes')||t.includes('self-host'))return'Enterprise Deployment';return'App Builder'}
function normalizeIssue(x){const body=(x.body||'').trim();const labels=(x.labels||[]).map(l=>typeof l==='string'?l:l.name).join(' ').toLowerCase();const severity=labels.includes('critical')||labels.includes('security')?'S1':labels.includes('bug')?'S2':labels.includes('enhancement')?'S4':'S3';const reactions=(x.reactions&&x.reactions.total_count)||0;return{id:'GH-'+x.number,source:'GitHub',account:'Public issue',segment:'Public',title:x.title,raw:body||'No issue body provided.',area:inferArea((x.title||'')+' '+body),severity,impact:Math.min(5,Math.max(2,Math.round(2+(x.comments||0)/5))),reach:Math.min(5,1+Math.round(reactions/3)),evidence:5,created:x.created_at,url:x.html_url,state:'Awaiting review',summary:(x.title||'').replace(/^\[.*?\]\s*/,'').slice(0,170),action:'Reproduce or validate the user impact, then decide whether this needs a fix, documentation change or further discovery.',notes:''}}
function signals(){return[...github,...synthetic].map(s=>({...s,...(decisions[s.id]||{})}))}
function pill(s){return'<span class="pill '+s.toLowerCase()+'">'+s+'</span>'}
function page(id){document.querySelectorAll('.page').forEach(x=>x.classList.add('hidden'));document.getElementById(id).classList.remove('hidden');document.querySelectorAll('.nav').forEach(x=>x.classList.toggle('active',x.dataset.page===id));if(id==='overview')renderOverview();if(id==='inbox')renderInbox();if(id==='review')renderReview()}
document.querySelectorAll('.nav').forEach(x=>x.onclick=()=>page(x.dataset.page));

function bars(target,obj){const max=Math.max(1,...Object.values(obj));document.getElementById(target).innerHTML=Object.entries(obj).sort((a,b)=>b[1]-a[1]).map(([k,v])=>'<div class="bar"><span>'+esc(k)+'</span><div class="track"><div class="fill" style="width:'+(v/max*100)+'%"></div></div><strong>'+v+'</strong></div>').join('')}

function renderOverview(){const a=signals();document.getElementById('mTotal').textContent=a.length;document.getElementById('mReview').textContent=a.filter(s=>s.state==='Awaiting review').length;document.getElementById('mHigh').textContent=a.filter(s=>['S1','S2'].includes(s.severity)).length;document.getElementById('mApproved').textContent=a.filter(s=>s.state==='Approved').length;const areas={};a.forEach(s=>areas[s.area]=(areas[s.area]||0)+1);bars('areaBars',areas);bars('sourceBars',{'GitHub':a.filter(s=>s.source==='GitHub').length,'Synthetic customer':a.filter(s=>s.source==='Synthetic customer').length});document.getElementById('topRows').innerHTML=[...a].sort((x,y)=>score(y)-score(x)).slice(0,8).map(s=>'<tr data-id="'+s.id+'"><td><strong>'+esc(s.title)+'</strong></td><td>'+esc(s.source)+'</td><td>'+esc(s.area)+'</td><td>'+pill(s.severity)+'</td><td><strong>'+score(s)+'</strong></td><td>'+esc(s.state)+'</td></tr>').join('');document.querySelectorAll('#topRows tr').forEach(r=>r.onclick=()=>openSignal(r.dataset.id))}

function renderInbox(){const q=document.getElementById('search').value.toLowerCase();const sf=document.getElementById('sourceFilter').value;const vf=document.getElementById('severityFilter').value;const st=document.getElementById('stateFilter').value;const a=signals().filter(s=>(!q||(s.title+' '+s.raw+' '+s.area).toLowerCase().includes(q))&&(sf==='all'||s.source===sf)&&(vf==='all'||s.severity===vf)&&(st==='all'||s.state===st));document.getElementById('inboxRows').innerHTML=a.length?a.map(s=>'<tr data-id="'+s.id+'"><td><strong>'+esc(s.title)+'</strong><br><small>'+esc(s.id)+'</small></td><td>'+esc(s.source)+'</td><td>'+esc(s.area)+'</td><td>'+pill(s.severity)+'</td><td>'+s.impact+'/5</td><td><strong>'+score(s)+'</strong></td><td>'+esc(s.state)+'</td></tr>').join(''):'<tr><td colspan="7">No signals match these filters.</td></tr>';document.querySelectorAll('#inboxRows tr[data-id]').forEach(r=>r.onclick=()=>openSignal(r.dataset.id))}
['search','sourceFilter','severityFilter','stateFilter'].forEach(id=>document.getElementById(id).addEventListener('input',renderInbox));

function openSignal(id){selected=signals().find(s=>s.id===id);page('review')}
function renderReview(){if(!selected){document.getElementById('reviewEmpty').classList.remove('hidden');document.getElementById('reviewContent').classList.add('hidden');return}document.getElementById('reviewEmpty').classList.add('hidden');document.getElementById('reviewContent').classList.remove('hidden');const s=signals().find(x=>x.id===selected.id)||selected;selected=s;document.getElementById('rSource').textContent=s.source;document.getElementById('rRef').textContent=s.id;document.getElementById('rCreated').textContent=new Date(s.created).toLocaleString();document.getElementById('rRaw').textContent=s.raw;document.getElementById('rLink').innerHTML=s.url?'<a href="'+s.url+'" target="_blank" rel="noreferrer">Open original GitHub issue ↗</a>':'Synthetic demo record. No real customer is represented.';document.getElementById('fSummary').value=s.summary||s.title;document.getElementById('fArea').innerHTML=AREAS.map(a=>'<option '+(a===s.area?'selected':'')+'>'+a+'</option>').join('');document.getElementById('fSeverity').value=s.severity;document.getElementById('fAction').value=s.action||'';document.getElementById('fNotes').value=s.notes||'';document.getElementById('sImpact').textContent=s.impact;document.getElementById('sReach').textContent=s.reach;document.getElementById('sEvidence').textContent=s.evidence;document.getElementById('sPriority').textContent=score(s)}
document.getElementById('fSeverity').onchange=()=>{if(selected){selected.severity=document.getElementById('fSeverity').value;document.getElementById('sPriority').textContent=score(selected)}};
document.querySelectorAll('[data-decision]').forEach(b=>b.onclick=()=>{if(!selected)return;const d={state:b.dataset.decision,summary:document.getElementById('fSummary').value,area:document.getElementById('fArea').value,severity:document.getElementById('fSeverity').value,action:document.getElementById('fAction').value,notes:document.getElementById('fNotes').value,reviewedAt:new Date().toISOString(),reviewedBy:'Demo PM'};decisions[selected.id]={...(decisions[selected.id]||{}),...d};localStorage.setItem('signalops_decisions',JSON.stringify(decisions));selected={...selected,...d};renderReview();renderOverview()});

async function loadGitHub(){try{const res=await fetch('https://api.github.com/repos/ToolJet/ToolJet/issues?state=open&per_page=30&sort=updated&direction=desc',{headers:{Accept:'application/vnd.github+json'}});if(!res.ok)throw new Error('GitHub '+res.status);const data=await res.json();github=data.filter(x=>!x.pull_request).map(normalizeIssue).slice(0,20);document.getElementById('sourceStatus').textContent='Live: '+github.length+' public GitHub issues loaded'}catch(e){github=[];document.getElementById('sourceStatus').textContent='GitHub unavailable; synthetic demo remains usable'}renderOverview();renderInbox()}
loadGitHub();renderOverview();